---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	router(router)
	select_hotel(select_hotel)
	finalize(finalize)
	new_trip_or_edit(new_trip_or_edit)
	edit_draft(edit_draft)
	chat_agent(chat_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> router;
	edit_draft -.-> __end__;
	edit_draft -.-> chat_agent;
	new_trip_or_edit -.-> __end__;
	new_trip_or_edit -.-> chat_agent;
	new_trip_or_edit -.-> edit_draft;
	router -.-> finalize;
	router -. &nbsp;chat&nbsp; .-> new_trip_or_edit;
	router -.-> select_hotel;
	select_hotel -.-> __end__;
	select_hotel -.-> new_trip_or_edit;
	select_hotel -.-> router;
	chat_agent --> __end__;
	finalize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
