/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/hotel-amenities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hotel Amenity Catalog
         * @description Return approved hotel-scoped catalog entries for client-side filtering.
         */
        get: operations["hotel_amenity_catalog_api_v1_hotel_amenities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/{hotel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotel Detail */
        get: operations["hotel_detail_api_v1_hotels__hotel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attractions/{attraction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attraction Detail */
        get: operations["attraction_detail_api_v1_attractions__attraction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Booking */
        post: operations["create_booking_api_v1_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Booking Endpoint */
        post: operations["confirm_booking_endpoint_api_v1_bookings__booking_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking Endpoint */
        post: operations["cancel_booking_endpoint_api_v1_bookings__booking_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Tạo một phiên chat mới và trả về session_id do server cấp.
         *
         *     Deliberately does NOT persist here. It used to, so the session would show
         *     up as its own row in the history rail right away — but an unstarted
         *     session (no chat turn yet) has nothing to summarize, so every one of
         *     those rows rendered as an indistinguishable, contentless "Chuyến đi mới"
         *     entry — the accumulating-empty-history bug this fixes. The in-memory
         *     registry entry created below already makes every other "+ Chuyến đi mới"
         *     click behave correctly (a fresh, empty main chat panel); the first *real*
         *     persisted row appears once a chat turn runs, written by `_persist_turn`
         *     below. (Until that writer existed, this docstring pointed at
         *     `persist_hook(session)` and "process_chat_turn and friends" — a cascade
         *     the graph cutover deleted, which is exactly how the history rail came to
         *     be permanently empty with no test failing.) list_sessions() additionally
         *     requires at least one chat_messages row per session, so any
         *     already-persisted empty rows from before this change stay hidden too.
         */
        post: operations["create_session_api_v1_chat_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persisted Sessions */
        get: operations["list_persisted_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{session_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Restore Session
         * @description Rehydrate a past conversation for the frontend.
         *
         *     Every field is built by the same helpers `respond` uses for a live turn
         *     (`agents/graph/response_payload.py`) — a restored conversation and the turn
         *     that produced it must not be able to disagree.
         *
         *     `suggestions` is deliberately empty, and is not an oversight: a suggestion
         *     belongs to one specific turn ("đặt khách sạn này?"), not to durable session
         *     state. Replaying a stale one next to a conversation the user left days ago
         *     would be worse than showing none.
         *
         *     A session that exists but has never run a turn restores as a valid empty
         *     payload rather than 404. 404 tells the frontend the server lost the
         *     session, and it responds by silently creating a new one — throwing away the
         *     id the user is currently sitting on.
         */
        get: operations["restore_session_api_v1_chat__session_id__restore_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Plan
         * @description Trả về kế hoạch chuyến đi hiện tại của một phiên, hoặc 404 nếu phiên không
         *     tồn tại/không thuộc về caller. A session that exists but hasn't run a graph
         *     turn yet (no checkpointed state) is a legitimate empty-plan session, not a
         *     404 -- ownership is already the existence check here.
         */
        get: operations["get_session_plan_api_v1_session__session_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{session_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Plan
         * @description Trả về kế hoạch chuyến đi hiện tại của một phiên, hoặc 404 nếu phiên không
         *     tồn tại/không thuộc về caller. A session that exists but hasn't run a graph
         *     turn yet (no checkpointed state) is a legitimate empty-plan session, not a
         *     404 -- ownership is already the existence check here.
         */
        get: operations["get_session_plan_api_v1_chat__session_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Xóa một phiên chat. Trả về 204 dù phiên có tồn tại hay không.
         *
         *     If the session exists but belongs to someone else, this stays a silent
         *     no-op — still 204, preserving the existing "204 either way" contract —
         *     but nothing is actually deleted. No new observable status code, so this
         *     never leaks "this session_id exists, it's just not yours."
         */
        delete: operations["delete_session_api_v1_chat__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Hotel */
        post: operations["select_hotel_api_v1_hotels_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/select_hotel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Hotel */
        post: operations["select_hotel_api_v1_chat_select_hotel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hotels/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Hotel */
        post: operations["change_hotel_api_v1_hotels_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planner Chat */
        post: operations["planner_chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner_chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planner Chat */
        post: operations["planner_chat_api_v1_planner_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner_chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Planner Chat Stream */
        post: operations["planner_chat_stream_api_v1_planner_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Status
         * @description Kiểm tra trạng thái agent.
         */
        get: operations["agent_status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search_attractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Attractions
         * @description Tìm kiếm semantic cho attractions sử dụng Supabase RPC.
         */
        get: operations["search_attractions_api_v1_search_attractions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search_hotels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Hotels
         * @description Tìm kiếm semantic cho hotels và rooms sử dụng Supabase RPC.
         */
        get: operations["search_hotels_api_v1_search_hotels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmenityCatalogPayload
         * @description Approved hotel amenity exposed to the browser for filters and pills.
         */
        AmenityCatalogPayload: {
            /** Id */
            id: string;
            /** Label Vi */
            label_vi: string;
            /** Label En */
            label_en: string;
            /** Category */
            category: string;
            /** Icon Key */
            icon_key: string | null;
        };
        /** AttractionDetailPayload */
        AttractionDetailPayload: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Category */
            category: string | null;
            /** Is Tour */
            is_tour: boolean | null;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number | null;
            /** Opening Time */
            opening_time: string | null;
            /** Closing Time */
            closing_time: string | null;
            /** Ticket Price Adult */
            ticket_price_adult: number | null;
            /** Ticket Price Child */
            ticket_price_child: number | null;
            /** Rating */
            rating: number | null;
            /** Review Count */
            review_count: number | null;
            /** Coordinates */
            coordinates: string | null;
            /** Images */
            images: string[] | null;
        };
        /** BookingOwnershipRequest */
        BookingOwnershipRequest: {
            /** Temporary User Ref */
            temporary_user_ref: string;
        };
        /** BookingPayload */
        BookingPayload: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /**
             * Check In Date
             * Format: date
             */
            check_in_date: string;
            /**
             * Check In Time
             * Format: time
             */
            check_in_time: string;
            /**
             * Check Out Date
             * Format: date
             */
            check_out_date: string;
            /**
             * Check Out Time
             * Format: time
             */
            check_out_time: string;
            /** Room Count */
            room_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RESERVED" | "CONFIRMED" | "CANCELLED" | "EXPIRED";
            /** Expires At */
            expires_at?: string | null;
            /** Total Amount */
            total_amount?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** BookingReservationRequest */
        BookingReservationRequest: {
            /**
             * Room Id
             * Format: uuid
             */
            room_id: string;
            /** Temporary User Ref */
            temporary_user_ref: string;
            /**
             * Check In Date
             * Format: date
             */
            check_in_date: string;
            /**
             * Check In Time
             * Format: time
             * @default 14:00:00
             */
            check_in_time: string;
            /**
             * Check Out Date
             * Format: date
             */
            check_out_date: string;
            /**
             * Check Out Time
             * Format: time
             * @default 12:00:00
             */
            check_out_time: string;
            /**
             * Room Count
             * @default 1
             */
            room_count: number;
            /** Total Amount */
            total_amount?: number | string | null;
            /** Currency */
            currency?: string | null;
        };
        /** ChangeHotelRequest */
        ChangeHotelRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** DayPlan */
        DayPlan: {
            /** Day Number */
            day_number: number;
            /** Theme */
            theme: string;
            /** Items */
            items: components["schemas"]["ItineraryItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HotelDetailPayload */
        HotelDetailPayload: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Star Rating */
            star_rating: number | null;
            /** Description */
            description: string | null;
            /** Address */
            address: string | null;
            /** City */
            city: string | null;
            /** Area Name */
            area_name: string | null;
            /** Location Highlight */
            location_highlight: string | null;
            /** Coordinates */
            coordinates: string | null;
            /** Image Url */
            image_url: string | null;
            /** Images */
            images: string[] | null;
            /** Amenities */
            amenities: string[] | null;
            /** Amenity Groups */
            amenity_groups: {
                [key: string]: unknown;
            } | null;
            /** Awards */
            awards: string[] | null;
            /** Warnings */
            warnings: string[] | null;
            /** Review Score */
            review_score: number | null;
            /** Review Count */
            review_count: number | null;
            /** Category Scores */
            category_scores: {
                [key: string]: unknown;
            } | null;
            /** Check In Time */
            check_in_time: string | null;
            /** Check In Until */
            check_in_until: string | null;
            /** Check Out Time */
            check_out_time: string | null;
            /** Reception Open Until */
            reception_open_until: string | null;
            /** Nearby Attractions */
            nearby_attractions: components["schemas"]["NearbyPlacePayload"][] | null;
            /** Nearby Essentials */
            nearby_essentials: unknown | null;
            /** Lowest Price */
            lowest_price: number | null;
            /** Currency */
            currency: string | null;
            /**
             * Available Room Count
             * @description Sum of booking-aware remaining room units across this hotel
             */
            available_room_count: number | null;
            /** Rooms */
            rooms: components["schemas"]["RoomDetailPayload"][];
            /**
             * Room Amenities
             * @description Unique approved room amenity catalog records for all returned rooms
             */
            room_amenities: components["schemas"]["AmenityCatalogPayload"][];
            /** Source Platform */
            source_platform: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /**
         * HotelOption
         * @description One hotel in the pending selection list sent to the React UI.
         *
         *     index is the 1-based ordinal that must equal suggestions[i].value (as int)
         *     for the same turn — they are two views of one list and must not disagree.
         */
        HotelOption: {
            /**
             * Index
             * @description Thứ tự 1-based; khớp với suggestions[i].value
             */
            index: number;
            /**
             * Id
             * @description UUID khách sạn
             */
            id: string;
            /**
             * Name
             * @description Tên khách sạn
             */
            name: string;
            /**
             * Star Rating
             * @description Hạng sao
             */
            star_rating: number | null;
            /**
             * Description
             * @description Mô tả ngắn
             */
            description: string | null;
            /**
             * Matched Rooms
             * @description Tên phòng phù hợp
             */
            matched_rooms: string[];
            /**
             * Average Nightly Price
             * @description Giá trung bình mỗi đêm theo ngày ở
             */
            average_nightly_price: number | null;
            /**
             * Total Stay Price
             * @description Tổng giá cho toàn bộ số đêm
             */
            total_stay_price: number | null;
            /**
             * Stay Night Count
             * @description Số đêm đã báo giá
             */
            stay_night_count: number | null;
            /**
             * Currency
             * @description Đơn vị tiền tệ của báo giá
             */
            currency: string | null;
            /**
             * Coordinates
             * @description Tọa độ lat,lng của khách sạn
             */
            coordinates: string | null;
            /** Address */
            address: string | null;
            /** Area Name */
            area_name: string | null;
            /** Image Url */
            image_url: string | null;
            /** Amenities */
            amenities: string[];
            /**
             * Display Amenities
             * @description Tối đa bốn tiện ích nổi bật để hiển thị trên thẻ khách sạn
             */
            display_amenities: string[];
            /** Review Score */
            review_score: number | null;
            /** Review Count */
            review_count: number | null;
            /** Match Score */
            match_score: number | null;
            /** Match Reasons */
            match_reasons: components["schemas"]["MatchReasonPayload"][];
            /** City */
            city: string | null;
        };
        /**
         * IntakeStatus
         * @description Snapshot of what the intake gate has collected so far.
         */
        IntakeStatus: {
            /** Destination */
            destination: string | null;
            /** Duration */
            duration: string | null;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** People */
            people: string | null;
            /**
             * Preferences
             * @description Travel-style labels
             */
            preferences: string[];
            /** Companions */
            companions: string | null;
            /** Pace */
            pace: string | null;
            /** Day Rhythm */
            day_rhythm: string[];
            /**
             * Notes
             * @description Free-text other needs
             * @default
             */
            notes: string;
            /**
             * Available Destinations
             * @description Real destinations the intake picker may choose from
             */
            available_destinations: string[];
            /**
             * Budget Options
             * @description Real budget/accommodation tier labels from hotel_selection
             */
            budget_options: string[];
            /** Min Price */
            min_price: number | null;
            /** Max Price */
            max_price: number | null;
            /**
             * Budget Skipped
             * @description True when the user explicitly opted out of a budget preference
             * @default false
             */
            budget_skipped: boolean;
            /**
             * Missing
             * @description Names of fields still needed: 'destination', 'people', 'start_date', 'end_date'
             */
            missing: string[];
        };
        /** ItineraryItem */
        ItineraryItem: {
            /** Order Index */
            order_index: number;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Activity */
            activity: string | null;
            /** Kind */
            kind: string | null;
            /** Reference Type */
            reference_type: string | null;
            /** Reference Id */
            reference_id: string | null;
            /** Coordinates */
            coordinates: string | null;
            /** Image Url */
            image_url: string | null;
            route_to_next: components["schemas"]["RouteInfoPayload"] | null;
            route_from_hotel: components["schemas"]["RouteInfoPayload"] | null;
        };
        /**
         * MatchReasonPayload
         * @description One piece of ranking evidence behind "AI đề xuất vì…".
         *
         *     `code` is an i18n key the frontend owns (matchReason.*); `value` is the raw
         *     number or label it describes. The backend never sends display text — the
         *     shape `hotel_selection._match_reasons` has always produced, now declared so
         *     a generated client sees it instead of an open dict.
         */
        MatchReasonPayload: {
            /** Code */
            code: string;
            /** Value */
            value: number | string;
        };
        /**
         * NearbyPlacePayload
         * @description An entry of `hotels.nearby_attractions` (a jsonb column).
         *
         *     `extra="allow"` because these rows are crawled data: the four fields below
         *     are the ones the UI reads and were confirmed against real rows, but the
         *     column may carry more and dropping it on serialization would be a silent
         *     lie of a different kind.
         *
         *     `distance_text` is a pre-formatted Vietnamese string from the crawl — data,
         *     not a UI string. Clients should rebuild the figure from `distance_km` so it
         *     honours their locale.
         */
        NearbyPlacePayload: {
            /** Name */
            name: string | null;
            /** Category */
            category: string | null;
            /** Coordinates */
            coordinates: string | null;
            /** Distance Km */
            distance_km: number | null;
            /** Distance Text */
            distance_text: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * PlannerChatRequest
         * @description A chat turn. Every field here reaches the graph.
         *
         *     `stay_dates`, `min_price` and `max_price` used to be declared alongside
         *     `message`, guarded by a validator demanding "at least one of" them — and
         *     then dropped: `_run_turn_via_graph` only ever forwarded `message`. No
         *     client sent them either, so the contract was dead at both ends.
         *
         *     They were deleted rather than connected. Feeding structured values into
         *     `travel_state` means a path around `extract_patch -> validate_patch ->
         *     apply_patch`, and that pipeline is where ambiguity gets resolved (an
         *     unclear date pauses the turn to ask) and where every write is checked
         *     against `ALLOWED_PATHS`. A side door for three fields nobody uses is not
         *     worth a second, unvalidated way into the same slots. The widget's existing
         *     route — compose a sentence, let the extractor parse it — is slower by one
         *     LLM call and correct by construction. A fast structured path is a real
         *     design problem for its own plan, not a dormant field woken up.
         *
         *     `message` is required now, which is what the old validator was trying to
         *     say the long way around.
         */
        PlannerChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Message */
            message: string;
            /**
             * Language
             * @description UI language for this turn's reply (vi | en)
             * @default vi
             * @enum {string}
             */
            language: "vi" | "en";
        };
        /** PlannerChatResponse */
        PlannerChatResponse: {
            /** Session Id */
            session_id: string;
            /** Reply */
            reply: string;
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionPayload"][];
            /**
             * Stage
             * @enum {string}
             */
            stage: "intake" | "hotel_options" | "planned" | "error";
            /** Hotel Options */
            hotel_options: components["schemas"]["HotelOption"][];
            /**
             * Hotel Amenities
             * @description Unique approved amenity catalog records for all returned hotel options
             */
            hotel_amenities: components["schemas"]["AmenityCatalogPayload"][];
            trip_plan: components["schemas"]["TripPlanPayload"] | null;
            intake: components["schemas"]["IntakeStatus"] | null;
            /**
             * Requires Stay Dates
             * @default false
             */
            requires_stay_dates: boolean;
            /** Compound Min Price */
            compound_min_price: number | null;
            /** Compound Max Price */
            compound_max_price: number | null;
            /** All Preferences */
            all_preferences: components["schemas"]["PreferencePayload"][];
            /** Active Preferences */
            active_preferences: components["schemas"]["PreferencePayload"][];
            /** Suggested Places */
            suggested_places: components["schemas"]["SuggestedPlacePayload"][];
        };
        /** PreferencePayload */
        PreferencePayload: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** RestoredMessagePayload */
        RestoredMessagePayload: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "intake" | "hotel_options" | "planned" | "error";
            /** At */
            at: string;
        };
        /** RoomDetailPayload */
        RoomDetailPayload: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Bed Description */
            bed_description: string | null;
            /** Room Size Sqm */
            room_size_sqm: number | null;
            /** Max Guests */
            max_guests: number | null;
            /** View */
            view: string | null;
            /** Room Facilities */
            room_facilities: string[] | null;
            /** Images */
            images: string[] | null;
            price: components["schemas"]["RoomPricePayload"] | null;
            /**
             * Available Room Count
             * @description Booking-aware remaining room units for the requested stay
             */
            available_room_count: number | null;
        };
        /** RoomPricePayload */
        RoomPricePayload: {
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string | null;
            /** Check In Date */
            check_in_date: string | null;
            /** Check Out Date */
            check_out_date: string | null;
            /** Sold Out */
            sold_out: boolean | null;
            /** Package Details */
            package_details: string | null;
        };
        /** RouteInfoPayload */
        RouteInfoPayload: {
            /** Distance Km */
            distance_km: number;
            /** Duration Mins */
            duration_mins: number;
            /** Polyline */
            polyline: string;
            /** Profile */
            profile: string | null;
        };
        /** SelectHotelRequest */
        SelectHotelRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Hotel Id */
            hotel_id: string | number;
            /** Selection Message */
            selection_message?: string | null;
        };
        /** SessionListPayload */
        SessionListPayload: {
            /** Sessions */
            sessions: components["schemas"]["SessionSummaryPayload"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Has More */
            has_more: boolean;
        };
        /** SessionRestorePayload */
        SessionRestorePayload: {
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: components["schemas"]["RestoredMessagePayload"][];
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionPayload"][];
            /** Stage */
            stage: string;
            /** Hotel Options */
            hotel_options: components["schemas"]["HotelOption"][];
            /** Hotel Amenities */
            hotel_amenities: components["schemas"]["AmenityCatalogPayload"][];
            trip_plan: components["schemas"]["TripPlanPayload"] | null;
            intake: components["schemas"]["IntakeStatus"] | null;
        };
        /** SessionSummaryPayload */
        SessionSummaryPayload: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string | null;
            /** Destination */
            destination: string | null;
            /** Duration Days */
            duration_days: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "completed";
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /**
         * SuggestedPlacePayload
         * @description One place a worker is pointing the map at this turn — an `attractions`
         *     table row, not a `NearbyPlacePayload` (that one is crawled
         *     `hotels.nearby_attractions` jsonb data, no stable `id`). `id` lets the
         *     frontend key map markers and tell two same-named places apart.
         *
         *     Shared wire shape, not a `list_nearby`-only one: any worker that wants
         *     the map to show candidate places writes into `PlannerChatResponse.
         *     suggested_places` using this shape — `itinerary_node`'s `list_nearby`
         *     search is the first writer, an `edit_item` "suggest" reply is a plausible
         *     second one. One field, one frontend rendering/toggle path for both.
         */
        SuggestedPlacePayload: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string | null;
            /** Coordinates */
            coordinates: string | null;
            /** Description */
            description: string | null;
            /** Rating */
            rating: number | null;
        };
        /** SuggestionPayload */
        SuggestionPayload: {
            /**
             * Label
             * @description Chữ hiển thị trên nút gợi ý
             */
            label: string;
            /**
             * Value
             * @description Nội dung gửi đi khi bấm nút
             */
            value: string;
        };
        /** TripPlanHotel */
        TripPlanHotel: {
            /** Id */
            id: string | null;
            /** Name */
            name: string | null;
            /** Star Rating */
            star_rating: number | null;
            /** Description */
            description: string | null;
            /** Matched Rooms */
            matched_rooms: string[];
            /** Coordinates */
            coordinates: string | null;
            /** Image Url */
            image_url: string | null;
            /** Source Platform */
            source_platform: string | null;
            /** Source Url */
            source_url: string | null;
        };
        /**
         * TripPlanPayload
         * @description Phase 3 payload for the trip plan right panel.
         */
        TripPlanPayload: {
            /** Status */
            status: string;
            /** Destination */
            destination: string | null;
            /** Duration Days */
            duration_days: number;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Number Of Adults */
            number_of_adults: number | null;
            /** Budget */
            budget: number | null;
            /** Budget Currency */
            budget_currency: string;
            hotel: components["schemas"]["TripPlanHotel"] | null;
            /** Days */
            days: components["schemas"]["DayPlan"][];
            /** Adjustments */
            adjustments: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hotel_amenity_catalog_api_v1_hotel_amenities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmenityCatalogPayload"][];
                };
            };
        };
    };
    hotel_detail_api_v1_hotels__hotel_id__get: {
        parameters: {
            query?: {
                check_in?: string | null;
                check_out?: string | null;
            };
            header?: never;
            path: {
                hotel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelDetailPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attraction_detail_api_v1_attractions__attraction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attraction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttractionDetailPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking_api_v1_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingReservationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_booking_endpoint_api_v1_bookings__booking_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingOwnershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_endpoint_api_v1_bookings__booking_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingOwnershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_chat_session_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persisted_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_session_api_v1_chat__session_id__restore_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRestorePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_plan_api_v1_session__session_id__state_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_plan_api_v1_chat__session_id__plan_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_chat__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_hotel_api_v1_hotels_select_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectHotelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_hotel_api_v1_chat_select_hotel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectHotelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_hotel_api_v1_hotels_change_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeHotelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planner_chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planner_chat_api_v1_planner_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    planner_chat_stream_api_v1_planner_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannerChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    search_attractions_api_v1_search_attractions_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_hotels_api_v1_search_hotels_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
